"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-h8q@_w61ow*+ab9xm$0xn6d^6l&@(m%bq^ukmf7-j!2!2198hk'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    'core',
    'personel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'core.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_ALL_ORIGINS = True

# Gerçek e-posta gönderimi için SMTP backend aktif ediliyor
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Kullanacağınız e-posta servisinin SMTP adresi
EMAIL_HOST = 'smtp.gmail.com'  # Gmail yerine yandex için: 'smtp.yandex.com.tr', outlook için: 'smtp.office365.com'

# Port ve Güvenlik Ayarları
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Gönderici Hesap Bilgileri
EMAIL_HOST_USER = 'ecerkerem04@gmail.com'  # Maillerin hangi hesaptan çıkmasını istiyorsanız o adres

# ⚠️ ÖNEMLİ: Buraya normal e-posta şifrenizi değil, 
# e-posta sağlayıcınızdan aldığınız 16 haneli "Uygulama Şifresini (App Password)" yazmalısınız.
EMAIL_HOST_PASSWORD = 'aitb misj sfow dndo' 

# Sistem maillerinin üzerinde görünecek varsayılan gönderici adı/adresi
DEFAULT_FROM_EMAIL = '"Şirket Yönetim Paneli" <ecerkerem04@gmail.com>'