# Generated by Django 6.0.6 on 2026-07-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonu')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyonu / Görevi')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='İşe Giriş Tarihi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maaşı')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.tenant')),
            ],
        ),
    ]
