# Generated by Django 6.0.6 on 2026-07-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('can_view_employees', models.BooleanField(default=True, verbose_name='Personelleri Görüntüleyebilir')),
                ('can_add_employee', models.BooleanField(default=False, verbose_name='Personel Ekleyebilir')),
                ('can_edit_employee', models.BooleanField(default=False, verbose_name='Personel Düzenleyebilir')),
                ('can_delete_employee', models.BooleanField(default=False, verbose_name='Personel Silebilir')),
                ('can_view_salary', models.BooleanField(default=False, verbose_name='Maaş Bilgisini Görebilir')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_permissions', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'position_name')},
            },
        ),
    ]
